// TODO Implement this library.
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOxIs_ojbR1_2y1R0jg_e7o3RTX0_XsbI',
    appId: '1:543804983704:web:af04086b0b86d1123303ed',
    messagingSenderId: '543804983704',
    projectId: 'trashtracker-b61e0',
    authDomain: 'trashtracker-b61e0.firebaseapp.com',
    storageBucket: 'trashtracker-b61e0.appspot.com',
    measurementId: 'G-DQXVX1ZGS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6I2qzWLrIJqKkIDiluyTKHOzpAs7rmC0',
    appId: '1:543804983704:android:5dc8617e445162293303ed',
    messagingSenderId: '543804983704',
    projectId: 'trashtracker-b61e0',
    storageBucket: 'trashtracker-b61e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAThEzUUp_ZUg5dn4uKqrqPQvaeMlUhLCA',
    appId: '1:543804983704:ios:e581d3490769fc353303ed',
    messagingSenderId: '543804983704',
    projectId: 'trashtracker-b61e0',
    storageBucket: 'trashtracker-b61e0.appspot.com',
    iosClientId: '543804983704-6lae9svd7nessp5dotlfqj20902euifg.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}